.\" 
.\" Copyright (c) 2009 Gordon D. Carrie.  All rights reserved.
.\" 
.\" Please address questions and feedback to dev0@trekix.net
.\" 
.\" $Revision: $ $Date: $
.\"
.TH bighi 1 "Print a sequence of values"
.SH NAME
bighi \- print an exponentially increasing sequence of values
.SH SYNOPSIS
\fBbighi\fP \fIlo\fP \fIhi\fP \fIn\fP
.SH DESCRIPTION
\fBbighi\fP prints a sequence of \fIn\fP values from \fIlo\fP to \fIhi\fP with
bigger steps at high values.
.SH AUTHOR
Gordon Carrie (dev0@trekix.net)
