.\" 
.\" Copyright (c) 2009 Gordon D. Carrie.  All rights reserved.
.\" 
.\" Please address questions and feedback to dev0@trekix.net
.\" 
.\" $Revision: 1.1 $ $Date: 2009/09/15 21:43:02 $
.\"
.TH biglo 1 "Print a sequence of values"
.SH NAME
biglo \- print an exponentially increasing sequence of values
.SH SYNOPSIS
\fBbiglo\fP \fIlo\fP \fIhi\fP \fIn\fP
.SH DESCRIPTION
\fBbiglo\fP prints a sequence of \fIn\fP values from \fIlo\fP to \fIhi\fP with
bigger steps at low values.
.SH AUTHOR
Gordon Carrie (dev0@trekix.net)
