.\" 
.\" Copyright (c) 2009 Gordon D. Carrie
.\" All rights reserved.
.\" 
.\" Please address questions and feedback to dev0@trekix.net
.\" 
.\" $Revision: 1.1 $ $Date: 2009/09/17 19:50:41 $
.\"
.TH biglrg 1 "Print a sequence of values"
.SH NAME
biglrg \- print a sequence of values with bigger steps at large magnitude values
.SH SYNOPSIS
\fBbiglrg\fP \fIlo\fP \fIhi\fP \fIn\fP
.SH DESCRIPTION
\fBbiglrg\fP prints a sequence of \fIn\fP values from \fIlo\fP to \fIhi\fP with
bigger steps at large values (large absolute value).
.SH AUTHOR
Gordon Carrie (dev0@trekix.net)
